// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpkabwuwchpleosiepee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwa2Fid3V3Y2hwbGVvc2llcGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDYyNDksImV4cCI6MjA2NDA4MjI0OX0.xE5phKWdCynioRAqyz3rMk_02FrLqTMT_3ZgOJ4sRUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});