// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiprdsjwpzabcihbwmpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpcHJkc2p3cHphYmNpaGJ3bXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NDk2NjMsImV4cCI6MjA2NzQyNTY2M30.zf5gBgcs-jVe0oytUDBhmWLBhG9uCHAUP1Kq-tK_EIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});